// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXdwH7thh8u7Jdf_5Ff5GzB6cN6lsC2Ic',
    appId: '1:422119433890:web:ac5736f5e9ef108756d9fb',
    messagingSenderId: '422119433890',
    projectId: 'mychatapp-11d7e',
    authDomain: 'mychatapp-11d7e.firebaseapp.com',
    storageBucket: 'mychatapp-11d7e.appspot.com',
    measurementId: 'G-FF3PRW64EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbSLLjRDaFIDB8UKSy87_vegsuvuNauE',
    appId: '1:422119433890:android:8756f920842625ae56d9fb',
    messagingSenderId: '422119433890',
    projectId: 'mychatapp-11d7e',
    storageBucket: 'mychatapp-11d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyHbxtYKcaWkQdy2ConrEtKi4MYSPUsg',
    appId: '1:422119433890:ios:87d55c014368a8d256d9fb',
    messagingSenderId: '422119433890',
    projectId: 'mychatapp-11d7e',
    storageBucket: 'mychatapp-11d7e.appspot.com',
    iosClientId: '422119433890-5t8v5okpbnq9si2dougeg09ujib45ai6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyHbxtYKcaWkQdy2ConrEtKi4MYSPUsg',
    appId: '1:422119433890:ios:87d55c014368a8d256d9fb',
    messagingSenderId: '422119433890',
    projectId: 'mychatapp-11d7e',
    storageBucket: 'mychatapp-11d7e.appspot.com',
    iosClientId: '422119433890-5t8v5okpbnq9si2dougeg09ujib45ai6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );
}
